Took out edit menu in read only mode. Am I correct that we don't want anything from the Edit menu in read only mode(jalview for apollo is in read only mode).
Still need to disable dragging of gaps for read only.

Also went through all the menu items. A lot of them dont work (from
here at least) and either need to be fixed or removed/disabled until
they are fixed. Heres a listing from the todo list:

JV37) If you select View->Wrap Alignment (which is rather nice) and
you resize the jalview window bigger than the sequence you get an
exception:
java.lang.StringIndexOutOfBoundsException: String index out of range: -63
        at java.lang.String.substring(String.java:1525)
        at java.lang.String.substring(String.java:1492)
        at jalview.gui.DrawableSequence.drawText(DrawableSequence.java:204)
        at jalview.gui.DrawableSequence.drawSequence(DrawableSequence.java:141)
        at jalview.gui.SeqCanvas.drawPanel(SeqCanvas.java:342)
        at jalview.gui.SeqCanvas.paint(SeqCanvas.java:191)
        at javax.swing.JComponent.paintChildren(JComponent.java:498)
	...
JV38) colour text and black text menu items dont work right - whats
the purpose of colour text anyways? dont we always want black text?
JV39) Null pointer exception when hit "View in alignment editor"
button in Pairwise alignments window:
java.lang.NullPointerException
        at jalview.gui.ScaleCanvas.paint(ScaleCanvas.java:116)
        at javax.swing.JComponent.paintChildren(JComponent.java:498)
	...
JV40) Calc->Conservation menu item doesnt appear to do anything.
JV41) Align->Local Alignment get this message:
Exception : java.io.IOException: clustalw: not found
And then ya cant destroy the window it brings up - get this exception:
Exception occurred during event dispatching:
java.lang.NullPointerException
        at jalview.gui.ProgressFrame$ProgressWindowListener.windowClosing(ProgressFrame.java:46)
        at java.awt.Window.processWindowEvent(Window.java:812)
	...
JV42) in wrapped mode (View->Wrap alignment) the labels of the
sequences get blacked out
JV43) What it Run command suppose to do? What kind of file does it
want? I can only get it to elicit this exception:
Exception occurred during event dispatching:
java.lang.NullPointerException
        at java.io.File.<init>(File.java:180)
        at jalview.gui.popups.CommandPopup$RunCommandAction.applyAction(CommandPopup.java:70)
        at jalview.gui.menus.JalAction.actionPerformed(JalAction.java:110)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1450)
	...
JV44) Align->Remote alignment at EBI and Remote postal analysis at EBI
both give this message:
Socket Exception java.net.ConnectException: Connection refused
Should probably be disabled.
JV45) Align->Remote Jnet analysis at EBI brings up an error dialog
with meesage ERROR: JNET action not implemented.
Should probably be disabled for now.